migrate(
  (app) => {
    // Users placeholder (author for recipes / collections / selected_recipes)
    app
      .db()
      .newQuery(`
    INSERT OR IGNORE INTO users (id, name, email, created, updated)
    VALUES (
      'juq99gi95gizj1g',
      'Usuário Local',
      'local@biblioteca-culinaria.com',
      '2026-01-01 00:00:00.000Z',
      '2026-01-01 00:00:00.000Z'
    )
  `)
      .execute()

    // 1. Categories (10 items)
    const categories = [
      {
        id: 'w07frp7mq5n1c2t',
        name: 'Carnes',
        slug: 'carnes',
        description: 'Cortes bovinos, suínos, aves e preparos de caça.',
        color: '#B4553F',
      },
      {
        id: 'kyzo380gbz9z7s4',
        name: 'Entradas',
        slug: 'entradas',
        description: 'Pequenos pratos, canapés, bruschettas e antepastos.',
        color: '#5A7D8E',
      },
      {
        id: 'mfy0298jd07p8uv',
        name: 'Lanches',
        slug: 'lanches',
        description: '',
        color: '#B98A4F',
      },
      {
        id: 'ds0uxvexb4s4ev3',
        name: 'Massas',
        slug: 'massas',
        description: 'Massas frescas, secas, recheadas, risotos e molhos clássicos.',
        color: '#C29A3B',
      },
      {
        id: '7og9o9ge1c7ab0l',
        name: 'Molhos & Conservas',
        slug: 'molhos-conservas',
        description: 'Fundos, reduções, emulsões, picles e compotas.',
        color: '#8C6D4F',
      },
      {
        id: '1qsmth7dfiisfde',
        name: 'Peixes',
        slug: 'peixes',
        description: '',
        color: '#B98A4F',
      },
      {
        id: 'io42hqrqdh3kl44',
        name: 'Pães & Fermentados',
        slug: 'paes-fermentados',
        description: 'Pães artesanais, focaccias, brioches e massas fermentadas.',
        color: '#B98A4F',
      },
      {
        id: 'u07wm94f57ltivx',
        name: 'Saladas',
        slug: 'saladas',
        description: 'Saladas compostas, folhas frescas e vinagretes aromáticos.',
        color: '#3B7A57',
      },
      {
        id: 'jrurz240bvsdq2l',
        name: 'Sobremesas',
        slug: 'sobremesas',
        description: 'Confeitaria fina, tortas, doces e sobremesas clássicas.',
        color: '#8E5A78',
      },
      {
        id: 'gp0r5mnb3x78ibr',
        name: 'Vegetariano',
        slug: 'vegetariano',
        description: 'Pratos à base de legumes, grãos, cogumelos e queijos artesanais.',
        color: '#4C7A5B',
      },
    ]

    for (const cat of categories) {
      app
        .db()
        .newQuery(`
      INSERT OR IGNORE INTO categories (id, name, slug, description, color, created, updated)
      VALUES ({:id}, {:name}, {:slug}, {:description}, {:color}, '2026-01-01 00:00:00.000Z', '2026-01-01 00:00:00.000Z')
    `)
        .bind({
          id: cat.id,
          name: cat.name,
          slug: cat.slug,
          description: cat.description,
          color: cat.color,
        })
        .execute()
    }

    // 2. Techniques (11 items)
    const techniques = [
      {
        id: '8x34daskv521lbv',
        name: 'Banho maria',
        slug: 'banho-maria',
        description: 'Cozimento lento em em baixa temperatura',
      },
      {
        id: 'xoe3noh2zlm42fj',
        name: 'Cozido',
        slug: 'cozido',
        description: 'Preparo em meio líquido com temperatura branda e infusão de aromas.',
      },
      {
        id: '94f6muo6r06kqpe',
        name: 'Cru',
        slug: 'cru',
        description: '',
      },
      {
        id: 'iti1ktj4senrrfi',
        name: 'Defumado',
        slug: 'defumado',
        description: 'Exposição a fumaça de madeiras nobres para sabor e preservação.',
      },
      {
        id: '48gtns7lr4cuvrd',
        name: 'Fermentação',
        slug: 'fermentacao',
        description: 'Transformação biológica natural por leveduras e bactérias benéficas.',
      },
      {
        id: 'vryemo4ldy13a55',
        name: 'Forno',
        slug: 'assado',
        description: 'Cozimento lento ou médio em forno por calor seco e indireto.',
      },
      {
        id: 'k6dkthl2rz6cncm',
        name: 'Fritura profunda',
        slug: 'fritura-profunda',
        description: 'Imersão em óleo quente para textura externa crocante e interior macio.',
      },
      {
        id: 'fnh60eujqj5wzaf',
        name: 'Grelhado',
        slug: 'grelhado',
        description: 'Cozimento rápido sob calor direto intenso, criando crosta caramelizada.',
      },
      {
        id: '0f9ilablmvmjbn9',
        name: 'Refogado',
        slug: 'refogado',
        description: 'Salteado em gordura aromatizada com cebola, alho e ervas.',
      },
      {
        id: '2e9pv0iuy5oyikr',
        name: 'Sous-vide',
        slug: 'sous-vide',
        description: 'Cozimento a vácuo em banho-maria de temperatura precisamente controlada.',
      },
      {
        id: '01i6q3sjc6rsqrk',
        name: 'Tecnica livre',
        slug: 'tecnica-livre',
        description: 'Preparo sem nenhuma tecnica especifica, apenas misturar os ingredientes',
      },
    ]

    for (const tech of techniques) {
      app
        .db()
        .newQuery(`
      INSERT OR IGNORE INTO techniques (id, name, slug, description, created, updated)
      VALUES ({:id}, {:name}, {:slug}, {:description}, '2026-01-01 00:00:00.000Z', '2026-01-01 00:00:00.000Z')
    `)
        .bind({
          id: tech.id,
          name: tech.name,
          slug: tech.slug,
          description: tech.description,
        })
        .execute()
    }

    // 3. Recipes (16 items)
    const recipes = [
      {
        id: 'jvqla5a8c19ctn6',
        title: 'Bacalhau com broa portuguesa',
        slug: 'bacalhau-com-broa-portuguesa-dukm',
        category: '1qsmth7dfiisfde',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary:
          'O Bacalhau com Broa é um dos pratos mais emblemáticos e acolhedores da gastronomia tradicional portuguesa. A receita combina a suculência das postas de bacalhau assadas com o contraste crocante de uma...',
        cover: 'bacalhau_com_broa_tojtk7n8wi.webp',
        contains_gluten: 1,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 1,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'a 4 postas ou lombos de bacalhau bem dessalgados', quantity: '3', unit: '' },
          { name: 'broa de milho (cerca de 300g a 400g)', quantity: '1', unit: '' },
          { name: 'batatas pequenas (tipo "batatinha")', quantity: '400', unit: 'g' },
          { name: 'alho', quantity: '3', unit: 'dentes' },
          { name: 'azeite de oliva extra virgem', quantity: '', unit: 'a gosto' },
          { name: 'sal grosso', quantity: '', unit: 'a gosto' },
          { name: 'pimenta-do-reino preta moída na hora', quantity: '', unit: 'a gosto' },
          {
            name: 'azeitonas pretas portuguesas ou chilenas (opcional)',
            quantity: '',
            unit: 'a gosto',
          },
          { name: 'salsinha fresca picada para finalizar', quantity: '', unit: '' },
        ]),
        method: JSON.stringify([
          'Assar as batatas a murro: Lave bem as batatas com a casca. Coloque-as inteiras num tabuleiro, salpique com bastante sal grosso e adicione os 3 dentes de alho inteiros com casca esmagados. Leve ao forno pré-aquecido a 200°C por cerca de 40 minutos ou até que estejam macias por dentro e com a pele tostada.',
          'Enquanto as batatas assam, prepare a broa: esfarele a broa de milho grosseiramente com as mãos, sem triturar demais. Reserve.',
          'Retire as batatas do forno, dê um pequeno murro (aperte levemente) em cada uma para que estalem um pouco, e tempere com fios generosos de azeite. Disponha as postas de bacalhau entre as batatas.',
          'Cubra as postas com a broa esfarelada, regue tudo com mais azeite e leve de volta ao forno por mais 20 a 25 minutos (depende da espessura do bacalhau) ou até que a broa esteja dourada e crocante e o bacalhau cozido.',
          'Finalize com salsinha fresca e as azeitonas pretas (se usar). Sirva imediatamente.',
        ]),
        tips: '',
      },
      {
        id: 'rpqsxruc7xz6v4p',
        title: 'Bolo Fondant de Chocolate Amargo 70%',
        slug: 'bolo-fondant-de-chocolate-amargo',
        category: 'jrurz240bvsdq2l',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 8,
        yield_unit: 'fatias',
        portions: '1 fatia média de 100g',
        prep_minutes: 20,
        cook_minutes: 22,
        total_minutes: 42,
        cost: 26,
        calories: 340,
        protein: 5.8,
        carbs: 29.4,
        fat: 21.6,
        summary:
          'Sobremesa francesa aveludada com chocolate de origem, textura densa e cremosa no centro, servida morna.',
        cover: '',
        contains_gluten: 1,
        contains_dairy: 0,
        contains_eggs: 1,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'Chocolate meio amargo 70% cacau picado', quantity: '200', unit: 'g' },
          { name: 'Manteiga sem sal em cubos', quantity: '150', unit: 'g' },
          {
            name: 'Ovos caipiras inteiros em temperatura ambiente',
            quantity: '4',
            unit: 'unidades',
          },
          { name: 'Açúcar refinado', quantity: '120', unit: 'g' },
          { name: 'Farinha de trigo peneirada', quantity: '60', unit: 'g' },
          { name: 'Extrato de baunilha', quantity: '1', unit: 'colher de chá' },
          { name: 'Sal marinho', quantity: '1', unit: 'pitada' },
        ]),
        method: JSON.stringify([
          'Derreta o chocolate picado e a manteiga em banho-maria suave ou micro-ondas em potência média, mexendo até ficar homogêneo e brilhante.',
          'Em uma tigela grande, bata os ovos com o açúcar e o extrato de baunilha até obter uma mistura espumosa e clara (cerca de 60 segundos).',
          'Incorpore o chocolate derretido à mistura de ovos em movimentos suaves de baixo para cima.',
          'Peneire a farinha e o sal sobre a massa e incorpore delicadamente com uma espátula de silicone, sem bater.',
          'Distribua a massa em forminhas individuais untadas com manteiga e cacau em pó, preenchendo até ¾ da capacidade.',
          'Asse em forno pré‑aquecido a 200°C por 12 minutos para obter o centro cremoso, ou 15 minutos para uma textura mais firme. O topo deve ficar firme mas com o centro ainda tremendo levemente.',
          'Desenforme ainda morno com cuidado, polvilhe cacau em pó e sirva com creme de leite batido sem açúcar ou sorvete artesanal de creme.',
        ]),
        tips: 'Não asse em excesso para manter o coração aveludado e cremoso. Cada forno varia, verifique o centro aos 18 minutos.',
      },
      {
        id: 'jcd5dvv1oynx06n',
        title: 'Broa de milho portuguesa',
        slug: 'broa-de-milho-portuguesa-9f1e',
        category: 'io42hqrqdh3kl44',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: 'yt088_broa_de_milho_receita_ycijuy2csw.jpg',
        contains_gluten: 1,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'ESPONJA', quantity: '', unit: '---' },
          { name: 'farinha de trigo', quantity: '100', unit: 'g' },
          {
            name: 'fermento biológico seco instantâneo (ou 15 g de fermento fresco)',
            quantity: '5',
            unit: 'g',
          },
          { name: 'água morna', quantity: '150', unit: 'g' },
          { name: 'MASSA PRINCIPAL', quantity: '', unit: '---' },
          { name: 'fubá de milho amarelo (médio, não muito fino)', quantity: '320', unit: 'g' },
          { name: 'água fervente para escaldar o fubá', quantity: '320', unit: 'g' },
          { name: 'farinha de trigo (aproximadamente, veja o ponto)', quantity: '250', unit: 'g' },
          { name: 'sal', quantity: '10', unit: 'g' },
          {
            name: 'açúcar (opcional, só se gostar da broa levemente adocicada)',
            quantity: '15',
            unit: 'g',
          },
          { name: 'azeite de oliva ou manteiga', quantity: '30', unit: 'ml' },
        ]),
        method: JSON.stringify([
          'Escaldar o fubá: Em uma tigela, misture 320 g de fubá com 320 g de água fervendo. Misture bem com uma colher e deixe esfriar completamente (de 30 a 60 minutos).',
          'Preparar a esponja: Em outra tigela, misture 100 g de farinha de trigo, o fermento e 150 g de água morna. Deixe descansar por 30–40 minutos até borbulhar.',
          'Misturar as massas: Junte a esponja ao fubá escaldado e frio. Acrescente o sal, o açúcar (se usar) e o azeite. Misture bem.',
          'Adicionar a farinha: Aos poucos, vá incorporando a farinha restante (250 g iniciais). A massa fica bem grudenta e mole — é normal. Não coloque farinha demais.',
          'Sovar: Com a ajuda de uma espátula ou na batedeira com gancho, sove por cerca de 8–10 minutos até alisar.',
          'Descansar: Cubra e deixe dobrar de volume (1 h a 1h30).',
          'Modelar: Despeje sobre superfície enfarinhada, divida em 2 partes e modele bolas ou formato alongado. Coloque em assadeira.',
          'Descanso final: Deixe crescer mais 30–40 minutos.',
          'Assar: Forno pré-aquecido a 230°C. Borrife água no forno ou coloque uma forma com água no fundo. Asse por 10 min a 230°C, reduza para 200°C e asse mais 30–35 min até dourar bem.',
          'Resfriar: Espere esfriar completamente sobre grade antes de cortar.',
        ]),
        tips: '',
      },
      {
        id: 'ur01753dx1w7zoy',
        title: 'Crepioca de quínoa',
        slug: 'crepioca-de-quinoa-d2er',
        category: 'io42hqrqdh3kl44',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 1,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'ovos (60g cada)', quantity: '2', unit: 'uni' },
          { name: 'goma de tapioca', quantity: '50', unit: 'g' },
          { name: 'quinoa em flocos', quantity: '28', unit: 'g' },
          { name: 'sal', quantity: '1', unit: 'pitada' },
          { name: 'azeite para untar', quantity: '', unit: '' },
        ]),
        method: JSON.stringify([
          'Aviso importante: É importante que a frigideira seja antiaderente para a massa não grudar!',
          'Em uma tigela, misture todos os ingredientes.',
          'Unte uma frigideira com azeite e despeje a massa.',
          'Espere dourar e vire a crepioca.',
          'Cozinhe até o centro da massa não estar mais cru (cerca de 3 minutos cada lado).',
        ]),
        tips: '',
      },
      {
        id: '01mnozc41d4ir1d',
        title: 'Cuscuz Marroquino com Abobrinha e Grão-de-Bico',
        slug: 'cuscuz-marroquino-com-abobrinha-e-grao-de-bico-2dlt',
        category: 'u07wm94f57ltivx',
        technique: 'xoe3noh2zlm42fj',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary:
          'A mistura de abobrinha dourada, grão-de-bico, uva-passa e especiarias deixa tudo mais interessante',
        cover: 'cuzcus_nezhpo9pkf.webp',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: '(chá) de cuscuz marroquino', quantity: '1', unit: 'xícara' },
          { name: 'grão-de-bico cozido (1½ xícara [chá] de grãos)', quantity: '1', unit: 'lata' },
          { name: 'abobrinha', quantity: '1', unit: '' },
          { name: 'cebola', quantity: '½', unit: '' },
          { name: 'dentes de alho', quantity: '1', unit: '' },
          { name: 'água fervente', quantity: '1', unit: 'xícara' },
          { name: 'azeite', quantity: '', unit: 'a gosto' },
          { name: 'passas brancas (opcional)', quantity: '', unit: '' },
          { name: 'castanha de caju torrada (opcional)', quantity: '', unit: '' },
          { name: 'sal e pimenta-do-reino moída na hora', quantity: '', unit: 'a gosto' },
          { name: 'cominho em pó', quantity: '1', unit: 'colher de chá' },
          { name: 'raspas de 1 limão-siciliano', quantity: '', unit: '' },
        ]),
        method: JSON.stringify([
          'Leve uma chaleira (ou panela) com a água ao fogo alto para ferver.\nNuma tigela média, coloque o cuscuz marroquino, tempere com 1 colher (chá) de sal, regue com a água fervente, misture 1 colher (sopa) de azeite, mexa delicadamente com um garfo e tampe. Reserve até que a água seja absorvida, por cerca de 5 minutos.',
          'Enquanto o cuscuz hidrata, prepare os legumes: descasque e pique fino a cebola e o alho. Lave, seque e corte a abobrinha ao meio, no sentido do comprimento, e cada metade em meias-luas de cerca de 1 cm na transversal.',
          'Leve uma frigideira grande ao fogo médio. Quando aquecer, regue com 2 colheres (sopa) de azeite, junte a cebola e tempere com uma pitada de sal. Refogue por cerca de 5 minutos, até começar a dourar. Acrescente o alho e mexa por 1 minuto. Adicione a abobrinha, tempere com sal e pimenta e refogue por mais 3 minutos, até ficar macia mas ainda firme.',
          'Enquanto isso, lave o grão-de-bico cozido em água corrente e deixe escorrer. Após os 5 minutos de hidratação, solte os grãos de cuscuz com um garfo.',
          'Junte o grão-de-bico e o cominho à frigideira com a abobrinha, tempere com sal e pimenta. Adicione o cuscuz marroquino hidratado e as raspas de limão-siciliano, mexa bem e deixe cozinhar por 2 minutos para esquentar e absorver os sabores. Sirva com castanha de caju torrada e passas brancas (opcional).',
        ]),
        tips: '',
      },
      {
        id: 'wxa1xo0pyu32au0',
        title: 'Cuscuz Marroquino com Damasco e Azeitona',
        slug: 'cuscuz-marroquino-com-damasco-e-azeitona-4ry6',
        category: 'u07wm94f57ltivx',
        technique: '8x34daskv521lbv',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary:
          'A combinação de damasco, cebola dourada, pistache, azeitona e canela cria um prato cheio de texturas e contrastes: tem o adocicado da fruta, o salgadinho da azeitona e o perfume das especiarias.',
        cover: 'cuzcus_kncmkrwouv.webp',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: '#INGREDIENTES', quantity: '', unit: '' },
          { name: '½ xícara (chá) de cuscuz marroquino', quantity: '1', unit: '' },
          { name: '½ xícara (chá) de água fervente', quantity: '1', unit: '' },
          { name: 'cebola roxa', quantity: '½', unit: '' },
          { name: 'damasco seco', quantity: '8', unit: 'unidades' },
          {
            name: 'azeitona preta (chilena, argentina ou a sua preferida)',
            quantity: '8',
            unit: 'unidades',
          },
          { name: 'pistache cru e sem casca', quantity: '1', unit: 'colher de sopa' },
          { name: 'azeite', quantity: '', unit: 'a gosto' },
          { name: 'canela em pó', quantity: '¼', unit: 'colher de chá' },
          { name: 'sal e pimenta-do-reino moída na hora', quantity: '', unit: 'a gosto' },
        ]),
        method: JSON.stringify([
          'Descasque e corte a cebola em fatias finas, no sentido do comprimento. Corte cada damasco ao meio, no sentido do comprimento, e fatie em pedaços de cerca de 1 cm. Corte a azeitona em lascas, ao redor do caroço, e descarte os caroços.',
          'Leve uma frigideira antiaderente ao fogo médio. Quando aquecer, regue com 1 colher (sopa) de azeite, adicione a cebola com uma pitada de sal e refogue por 2 minutos até murchar. Acrescente o damasco e a canela e mexa por mais 2 minutos para perfumar. Adicione a azeitona e refogue por 1 minuto — atenção: a azeitona solta sal; prove antes de adicionar mais sal. Desligue o fogo.',
          'Enquanto isso, prepare o cuscuz marroquino: numa tigela, coloque o cuscuz, tempere com uma pitada de sal e pimenta, regue com ½ xícara (chá) de água fervente, junte ½ colher (sopa) de azeite, mexa com um garfo e tampe. Deixe hidratar por 5 minutos.',
          'Após os 5 minutos, solte os grãos de cuscuz com um garfo e junte na frigideira com os ingredientes refogados. Misture bem e deixe cozinhar por 2 minutos em fogo médio. Sirva com pistache e raspas de limão siciliano (opcional).',
        ]),
        tips: '',
      },
      {
        id: '44pdvbobj9rgw8n',
        title: 'Galeto Grelhado com Ervas da Provence e Manteiga de Alho',
        slug: 'galeto-grelhado-com-ervas',
        category: 'w07frp7mq5n1c2t',
        technique: 'fnh60eujqj5wzaf',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 4,
        yield_unit: 'porções',
        portions: 'Meio galeto por pessoa',
        prep_minutes: 25,
        cook_minutes: 25,
        total_minutes: 50,
        cost: 32.5,
        calories: 450,
        protein: 42,
        carbs: 2.5,
        fat: 28,
        summary:
          'Galeto desossado marinado em vinho branco, alecrim, tomilho e raspas de limão siciliano, grelhado com crosta dourada perfeita.',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 1,
        contains_eggs: 0,
        contains_fish: 1,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          {
            name: 'Galetos inteiros abertos pela espinha (estilo borboleta)',
            quantity: '2',
            unit: 'unidades',
          },
          { name: 'Ramos de tomilho fresco e alecrim', quantity: '6', unit: 'ramos' },
          { name: 'Dentes de alho laminados', quantity: '6', unit: 'dentes' },
          { name: 'Suco de 1 ½ limão siciliano + raspas', quantity: '', unit: '' },
          { name: 'Azeite de oliva extra virgem', quantity: '80', unit: 'ml' },
          { name: 'Vinho branco seco', quantity: '100', unit: 'ml' },
          { name: 'Pimenta-do-reino preta moída grossa', quantity: '', unit: 'a gosto' },
          { name: 'Manteiga com sal em temperatura ambiente', quantity: '60', unit: 'g' },
          {
            name: 'Ramos de tomilho e alecrim picados para a manteiga',
            quantity: '2',
            unit: 'colheres de sopa',
          },
        ]),
        method: JSON.stringify([
          'Abra os galetos ao meio, seque bem a pele com papel toalha e tempere com a marinada de vinho branco, limão, azeite, alho e ervas picadas por 2 horas.',
          'Misture a manteiga amolecida com parte das ervas picadas e reserve em temperatura ambiente para untar durante a grelha.',
          'Pré-aqueça a grelha ou churrasqueira em fogo médio-alto (180–200°C). Grelhe o galeto com o lado da pele voltado para baixo por 15 minutos até a pele dourar intensamente e ficar crocante e com marcas da grelha.',
          'Pincele o lado de cima (sem pele) com a manteiga de ervas durante o cozimento. Vire com cuidado e grelhe por mais 10 minutos ou até que a carne alcance 74°C no centro. Deixe descansar 5 minutos antes de fatiar.',
        ]),
        tips: 'Secar a pele muito bem antes de grelhar é o segredo para obter uma textura incrivelmente crocante sem grudar na grelha.',
      },
      {
        id: '4it94vggpidx6m5',
        title: 'Granola de quínoa e cacau',
        slug: 'granola-de-quinoa-e-cacau-e8mu',
        category: 'jrurz240bvsdq2l',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'óleo de coco derretido', quantity: '55', unit: 'g' },
          { name: 'manteiga de amendoim', quantity: '62', unit: 'g' },
          { name: 'mel ou melado de cana', quantity: '40', unit: 'g' },
          { name: 'cacau em pó', quantity: '15', unit: 'g' },
          { name: 'canela em pó', quantity: '½', unit: 'colher de chá' },
          { name: 'quinoa estufada', quantity: '30', unit: 'g' },
          { name: 'aveia em flocos finos', quantity: '100', unit: 'g' },
          { name: 'coco em flocos (secos e sem açúcar)', quantity: '25', unit: 'g' },
          { name: 'flor de sal', quantity: '½', unit: 'colher de chá' },
        ]),
        method: JSON.stringify([
          'Em uma tigela grande, adicione o óleo de coco, a manteiga de amendoim, o mel e o cacau em pó. Misture bem até ficar homogêneo.',
          'Adicione a quinoa estufada e a aveia em flocos. Mexa bem até que toda a mistura líquida envolva os grãos.',
          'Adicione os flocos de coco e a flor de sal. Incorpore delicadamente.',
          'Transfira a massa para uma assadeira forrada com tapete de silicone ou papel manteiga. Pressione com as costas de uma colher para compactar e nivelar bem a superfície.',
          'Leve para assar em forno pré-aquecido a 160°C por 15–20 minutos, até secar.',
          'Retire do forno e aguarde esfriar completamente antes de quebrar em pedaços. Depois de fria, ficará crocante.',
        ]),
        tips: '',
      },
      {
        id: 'vmmil0mscobt5ub',
        title: 'Granola de quínoa, tangerina e coco',
        slug: 'granola-de-quinoa-tangerina-e-coco-vlgv',
        category: 'io42hqrqdh3kl44',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'amêndoas', quantity: '70', unit: 'g' },
          { name: 'amendoim', quantity: '70', unit: 'g' },
          { name: 'quinoa estufada', quantity: '15', unit: 'g' },
          { name: 'semente de girassol', quantity: '23', unit: 'g' },
          { name: 'coco em flocos desidratado e sem açúcar', quantity: '50', unit: 'g' },
          { name: 'açúcar mascavo', quantity: '25', unit: 'g' },
          { name: 'coco ralado grosso', quantity: '50', unit: 'g' },
          { name: 'óleo de coco', quantity: '17', unit: 'g' },
          { name: 'mel', quantity: '55', unit: 'g' },
          { name: 'raspas de 1 tangerina', quantity: '', unit: '' },
        ]),
        method: JSON.stringify([
          'Misture o mel com as raspas de tangerina. Em outro recipiente, misture todos os demais ingredientes e regue com a mistura de mel e tangerina.',
          'Transfira para uma assadeira forrada com tapete de silicone e asse em forno pré-aquecido a 150°C por aproximadamente 30 minutos, mexendo de vez em quando, até dourar. Deixe esfriar completamente (ela fica crocante depois de fria).',
        ]),
        tips: '',
      },
      {
        id: 'kk1hywa1t80at95',
        title: 'MOLHO DE GENGIBRE E MISSo',
        slug: 'molho-de-gengibre-e-misso-4ly0',
        category: '7og9o9ge1c7ab0l',
        technique: '48gtns7lr4cuvrd',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary:
          'O molho de gengibre e miso é um tempero cremoso e agridoce muito usado na culinária japonesa, ideal para saladas',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'pasta de miso branco', quantity: '3', unit: 'colheres de sopa' },
          { name: 'vinagre de arroz', quantity: '2', unit: 'colheres de sopa' },
          { name: 'óleo de gergelim', quantity: '1', unit: 'colher de sopa' },
          { name: 'gengibre ralado', quantity: '1', unit: 'colher de chá' },
          { name: 'molho shoyu', quantity: '1', unit: 'colher de sopa' },
          { name: 'água morna (se necessário)', quantity: '2', unit: 'colheres de sopa' },
          { name: 'pimenta-do-reino a gosto', quantity: '', unit: '' },
        ]),
        method: JSON.stringify(['**MOLHO DE GENGIBRE E MISO**']),
        tips: '',
      },
      {
        id: '59qeb8f84whi3qg',
        title: 'Moqueca Tradicional de Peixe e Camarão',
        slug: 'moqueca-tradicional-de-peixe-e-camarao',
        category: 'w07frp7mq5n1c2t',
        technique: 'xoe3noh2zlm42fj',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 6,
        yield_unit: 'porções',
        portions: '1 tigela individual com caldo e guarnições',
        prep_minutes: 30,
        cook_minutes: 30,
        total_minutes: 60,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary:
          'Receita costeira rica em leite de coco artesanal, azeite de dendê, robalho fresco e pimentões coloridos cozidos em panela de barro.',
        cover: '15166954828_moqueca_peixecama_site1_lcc0njlrlm.jpg',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'Postas de Robalo ou Badejo fresco', quantity: '1', unit: 'kg' },
          { name: 'Camarões médios limpos', quantity: '400', unit: 'g' },
          { name: 'Leite de coco artesanal espesso', quantity: '400', unit: 'ml' },
          { name: 'Azeite de dendê', quantity: '3', unit: 'colheres de sopa' },
          { name: 'Cebolas em rodelas finas', quantity: '3', unit: 'unidades' },
          {
            name: 'Pimentões verdes, vermelhos e amarelos em tiras finas',
            quantity: '3',
            unit: 'unidades',
          },
          {
            name: 'Tomates maduros sem pele e sem semente em cubos',
            quantity: '4',
            unit: 'unidades',
          },
          { name: 'Coentro fresco picado grosseiro', quantity: '1', unit: 'maço' },
          { name: 'Leite de coco para finalização a frio', quantity: '100', unit: 'ml' },
          { name: 'Suco de limão Tahiti', quantity: '1', unit: 'colher de sopa' },
          { name: 'Alho amassado', quantity: '4', unit: 'dentes' },
          { name: 'Sal marinho e pimenta-do-reino moída', quantity: '', unit: 'a gosto' },
        ]),
        method: JSON.stringify([
          'Marine as postas de peixe e os camarões com suco de limão, alho, sal e pimenta por 20 minutos.',
          'Na panela de barro aquecida, monte camadas com cebola, pimentões, tomates e postas de peixe temperadas. Regue com azeite de dendê.',
          'Adicione metade do coentro e o leite de coco. Tampe a panela e cozinhe em fogo baixo, sem mexer, entre 25 e 30 minutos.',
          'Nos últimos 7 minutos, coloque os camarões e mais um fio de azeite de dendê. Cozinhe até os camarões ficarem rosados e firmes.',
          'Retire do fogo: Agora é a hora de adicionar o leite de coco frio, cru. Isso cria um choque térmico que intensifica o perfume do coco. Salpique o coentro restante e regue com mais um fio de azeite de dendê.',
        ]),
        tips: 'Não mexa com colher durante o cozimento; apenas balance suavemente a panela pelas alças para integrar os sabores sem quebrar as postas.',
      },
      {
        id: 'x1jwfanehtfguu7',
        title: 'Panqueca de banana com trigo sarraceno',
        slug: 'panqueca-de-banana-com-trigo-sarraceno-y3ek',
        category: 'io42hqrqdh3kl44',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'farinha de trigo sarraceno', quantity: '72', unit: 'g' },
          { name: 'flocos de quinoa', quantity: '28', unit: 'g' },
          { name: 'polvilho doce', quantity: '18', unit: 'g' },
          { name: 'fermento em pó', quantity: '1', unit: 'colher de chá' },
          { name: 'banana nanica', quantity: '2', unit: 'uni' },
          { name: 'ovos (60g cada)', quantity: '2', unit: 'uni' },
          { name: 'óleo de coco ou outro', quantity: '15', unit: 'ml' },
          { name: 'pitada de sal', quantity: '', unit: '' },
        ]),
        method: JSON.stringify([
          'Em uma tigela, misture os ingredientes secos e reserve.',
          'Em outro recipiente, bata os ingredientes líquidos até que fiquem homogêneos e junte à tigela dos secos. Se a massa parecer grossa, adicione um pouco de leite ou água.',
          'Aqueça e unte uma frigideira com óleo de coco. Coloque pequenas porções de massa e abaixe o fogo. Tampe a frigideira para que o vapor ajude a assar a panqueca por dentro.',
          'Quando começar a secar e dourar por baixo, vire e deixe dourar o outro lado.',
        ]),
        tips: '',
      },
      {
        id: 'lhowxac3wpee40i',
        title: 'Panqueca salgada de beterraba',
        slug: 'panqueca-salgada-de-beterraba-whrx',
        category: 'mfy0298jd07p8uv',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 0,
        yield_unit: 'porções',
        portions: '',
        prep_minutes: 0,
        cook_minutes: 0,
        total_minutes: 0,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: 'massa_de_panqueca_de_beterraba_2_b8eq1w09ho.jpg',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 1,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'beterraba ralada em ralo fino', quantity: '110', unit: 'g' },
          { name: 'leite vegetal (usei de amêndoas)', quantity: '240', unit: 'ml' },
          { name: 'uni ovos (60g cada)', quantity: '2', unit: '' },
          { name: 'farinha de trigo', quantity: '130', unit: 'g' },
          { name: 'azeite', quantity: '30', unit: 'ml' },
          { name: 'pitada de sal a gosto', quantity: '', unit: '' },
        ]),
        method: JSON.stringify([
          'Em uma tigela, misture todos os ingredientes até formar uma massa uniforme. Deixe descansar por 10 minutos.',
          'Aqueça uma frigideira antiaderente em fogo médio-baixo. Coloque cerca de 1/4 de xícara de massa por panqueca, espalhando para cobrir o fundo.',
          'Cozinhe por 2–3 minutos de cada lado, até a panqueca estar levemente dourada. Para rechear, reaqueça em frigideira untada com azeite e adicione os recheios de sua preferência.',
        ]),
        tips: '',
      },
      {
        id: 'u9zh2a4krzt71dc',
        title: 'Pão Pita',
        slug: 'pao-pita-65mk',
        category: 'io42hqrqdh3kl44',
        technique: 'vryemo4ldy13a55',
        author: 'juq99gi95gizj1g',
        difficulty: 'Fácil',
        yield_quantity: 12,
        yield_unit: 'porções',
        portions: 'Pão de 60g',
        prep_minutes: 30,
        cook_minutes: 120,
        total_minutes: 150,
        cost: 0,
        calories: 0,
        protein: 0,
        carbs: 0,
        fat: 0,
        summary: '',
        cover: 'yt098_mini_pao_pita_receita_840x560_48umwnffxq.jpg',
        contains_gluten: 1,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'Farinha de trigo', quantity: '500', unit: 'g' },
          { name: 'Fermento biológico seco', quantity: '5', unit: 'g' },
          { name: 'Sal', quantity: '10', unit: 'g' },
          { name: 'Açũcar', quantity: '20', unit: 'g' },
          { name: 'Água morna', quantity: '280', unit: 'ml' },
          { name: 'Azeite de oliva', quantity: '30', unit: 'ml' },
        ]),
        method: JSON.stringify([
          'Dissolva o fermento na água morna.',
          'Acrescente 100 g de farinha e reserve por 20 minutos.',
          'Peneire o restante da farinha junto com o sal e o açúcar.',
          'Misture todos os ingredientes e sove até obter uma massa homogênea. Deixe a massa descansar por 40 minutos.',
          'Modele os pães em formato de disco com cerca de 0,5 cm de espessura e deixe descansar por mais 30 minutos.',
          'Aqueça uma frigideira grande, disponha os discos um a um e aguarde formar bolhas. Vire e aguarde dourar. Cuidado para não queimar.',
        ]),
        tips: 'Assa em menos de 1 minuto.',
      },
      {
        id: '3673d2jrng148w1',
        title: 'Pão de Fermentação Natural (Sourdough)',
        slug: 'pao-de-fermentacao-natural',
        category: 'io42hqrqdh3kl44',
        technique: '48gtns7lr4cuvrd',
        author: 'juq99gi95gizj1g',
        difficulty: 'Médio',
        yield_quantity: 1,
        yield_unit: 'unidades',
        portions: '1 pão de 850g (cerca de 12 fatias)',
        prep_minutes: 40,
        cook_minutes: 45,
        total_minutes: 85,
        cost: 14.5,
        calories: 180,
        protein: 6.2,
        carbs: 36.5,
        fat: 0.8,
        summary:
          'Pão rústico de casca crocante, miolo alvéolo aberto e aroma fermentado complexo feito com levain ativo.',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'Farinha de trigo especial (tipo 1 ou Manitoba)', quantity: '450', unit: 'g' },
          { name: 'Farinha de trigo integral fina', quantity: '50', unit: 'g' },
          { name: 'Água mineral fria (75% hidratação)', quantity: '375', unit: 'ml' },
          {
            name: 'Fermento natural (levain) ativo e alimentado 4h antes',
            quantity: '120',
            unit: 'g',
          },
          { name: 'Sal marinho', quantity: '12', unit: 'g' },
        ]),
        method: JSON.stringify([
          'Faça a autólise misturando as farinhas e 350ml de água até incorporar. Cubra e descanse por 45 minutos.',
          'Adicione o fermento natural (levain) ativo e sove delicadamente até incorporar por completo.',
          'Adicione o sal e o restante da água; sove com a técnica de coil fold (dobras em espiral) por 5 minutos até atingir uma massa lisa e elástica. Transfira para um bowl e deixe fermentar por 4 horas com dobras a cada 30 minutos.',
          'Modele com tensão superficial em formato boule (redondo) e deixe fermentar em cesta de banneton enfarinhada por 2 horas ou geladeira overnight.',
          'Asse em forno a 250°C em panela de ferro (dutch oven) tampada por 25 minutos, depois destampe e asse por mais 20 minutos a 220°C para formar a casca dourada.',
        ]),
        tips: 'Use água sem cloro para não inibir as leveduras selvagens. Espere o pão esfriar por pelo menos 2 horas antes de cortar para assentar a umidade do miolo.',
      },
      {
        id: '9bk39umkggg6ml8',
        title: 'Risoto de Cogumelos Porcini e Trufas',
        slug: 'risoto-de-cogumelos-porcini-e-trufas',
        category: 'ds0uxvexb4s4ev3',
        technique: '0f9ilablmvmjbn9',
        author: 'juq99gi95gizj1g',
        difficulty: 'Médio',
        yield_quantity: 4,
        yield_unit: 'porções',
        portions: '1 prato fundo generoso (cerca de 280g)',
        prep_minutes: 20,
        cook_minutes: 25,
        total_minutes: 45,
        cost: 48,
        calories: 420,
        protein: 11.5,
        carbs: 58,
        fat: 14.2,
        summary:
          'Clássico italiano com arroz carnaroli, mix de cogumelos frescos e porcini hidratados, finalizado com manteiga gelada e parmesão.',
        cover: '',
        contains_gluten: 0,
        contains_dairy: 0,
        contains_eggs: 0,
        contains_fish: 0,
        contains_honey: 0,
        contains_ave: 0,
        contains_camarao: 0,
        ingredients: JSON.stringify([
          { name: 'Arroz Carnaroli ou Arbóreo', quantity: '320', unit: 'g' },
          { name: 'Cogumelos Porcini secos', quantity: '30', unit: 'g' },
          { name: 'Cogumelos Paris e Shimeji frescos fatiados', quantity: '250', unit: 'g' },
          { name: 'Caldo de legumes caseiro quente', quantity: '1.2', unit: 'L' },
          { name: 'Vinho branco seco', quantity: '150', unit: 'ml' },
          { name: 'Cebola amarela em cubos finos', quantity: '1', unit: 'unidade' },
          { name: 'Azeite de oliva extra virgem', quantity: '3', unit: 'colheres de sopa' },
          { name: 'Manteiga sem sal gelada', quantity: '50', unit: 'g' },
          { name: 'Queijo parmesão ralado', quantity: '80', unit: 'g' },
          { name: 'Azeite trufado para finalização', quantity: '', unit: 'a gosto' },
          { name: 'Sal marinho e pimenta-do-reino', quantity: '', unit: 'a gosto' },
        ]),
        method: JSON.stringify([
          'Hidrate o Porcini em 200ml de água morna por 20 minutos. Coe a água e adicione-a à panela com o caldo de legumes aquecido.',
          'Em uma frigideira ampla, salteie os cogumelos frescos e o porcini no azeite em fogo alto até dourar completamente. Retire e reserve.',
          'Na mesma panela, refogue a cebola com mais azeite até translúcida. Adicione o arroz e mexa por 2 minutos para tostar e selar os grãos.',
          'Degele com o vinho branco e mexa até quase evaporar completamente.',
          'Adicione 1 concha do caldo quente e mexa vigorosamente. Sempre adicione a próxima concha quando a anterior estiver quase absorvida. Esse processo deve levar entre 16 e 18 minutos.',
          'Quando o arroz estiver al dente (cremoso mas com leve núcleo firme), desligue o fogo e incorpore a manteiga gelada e o parmesão com movimentos energéticos (mantecatura). Isso criará uma emulsão cremosa.',
          'Sirva imediatamente em pratos fundos aquecidos, adicione os cogumelos salteados sobre o risoto e finalize com azeite trufado e pimenta-do-reino moída na hora.',
        ]),
        tips: 'A manteiga deve estar obrigatoriamente gelada no momento da mantecatura para criar uma emulsão perfeita com o amido do arroz.',
      },
    ]

    for (const r of recipes) {
      app
        .db()
        .newQuery(`
      INSERT OR IGNORE INTO recipes (
        id, title, slug, summary, category, technique, cover, difficulty,
        yield_quantity, yield_unit, portions, prep_minutes, cook_minutes,
        total_minutes, cost, calories, protein, carbs, fat,
        ingredients, method, tips, author,
        contains_gluten, contains_dairy, contains_eggs, contains_fish, contains_honey, contains_ave, contains_camarao,
        created, updated
      ) VALUES (
        {:id}, {:title}, {:slug}, {:summary}, {:category}, {:technique}, {:cover}, {:difficulty},
        {:yield_quantity}, {:yield_unit}, {:portions}, {:prep_minutes}, {:cook_minutes},
        {:total_minutes}, {:cost}, {:calories}, {:protein}, {:carbs}, {:fat},
        {:ingredients}, {:method}, {:tips}, {:author},
        {:contains_gluten}, {:contains_dairy}, {:contains_eggs}, {:contains_fish}, {:contains_honey}, {:contains_ave}, {:contains_camarao},
        '2026-01-01 00:00:00.000Z', '2026-01-01 00:00:00.000Z'
      )
    `)
        .bind({
          id: r.id,
          title: r.title,
          slug: r.slug,
          summary: r.summary,
          category: r.category,
          technique: r.technique,
          cover: r.cover,
          difficulty: r.difficulty,
          yield_quantity: r.yield_quantity,
          yield_unit: r.yield_unit,
          portions: r.portions,
          prep_minutes: r.prep_minutes,
          cook_minutes: r.cook_minutes,
          total_minutes: r.total_minutes,
          cost: r.cost,
          calories: r.calories,
          protein: r.protein,
          carbs: r.carbs,
          fat: r.fat,
          ingredients: r.ingredients,
          method: r.method,
          tips: r.tips,
          author: r.author,
          contains_gluten: r.contains_gluten,
          contains_dairy: r.contains_dairy,
          contains_eggs: r.contains_eggs,
          contains_fish: r.contains_fish,
          contains_honey: r.contains_honey,
          contains_ave: r.contains_ave,
          contains_camarao: r.contains_camarao,
        })
        .execute()
    }

    // 4. Collections (1 item)
    const collections = [
      {
        id: '1ilu9i0atcmt3e9',
        name: 'Para imprimir',
        user: 'juq99gi95gizj1g',
        description: 'Imprimir etiquetas para o Buffet',
        share_token: '',
      },
    ]

    for (const col of collections) {
      app
        .db()
        .newQuery(`
      INSERT OR IGNORE INTO collections (id, name, user, description, share_token, created, updated)
      VALUES ({:id}, {:name}, {:user}, {:description}, {:share_token}, '2026-01-01 00:00:00.000Z', '2026-01-01 00:00:00.000Z')
    `)
        .bind({
          id: col.id,
          name: col.name,
          user: col.user,
          description: col.description,
          share_token: col.share_token,
        })
        .execute()
    }

    // 5. Collection Recipes (5 items)
    const collectionRecipes = [
      { id: 'px79sshg2r2ni8f', collection: '1ilu9i0atcmt3e9', recipe: '59qeb8f84whi3qg' },
      { id: 'dso1c5l0r23dfyt', collection: '1ilu9i0atcmt3e9', recipe: '9bk39umkggg6ml8' },
      { id: 'jfbcafinmqw0fhw', collection: '1ilu9i0atcmt3e9', recipe: '3673d2jrng148w1' },
      { id: 'vf5ti0fdvdxun8s', collection: '1ilu9i0atcmt3e9', recipe: 'rpqsxruc7xz6v4p' },
      { id: '0kgb9sq8ijflowv', collection: '1ilu9i0atcmt3e9', recipe: '44pdvbobj9rgw8n' },
    ]

    for (const cr of collectionRecipes) {
      app
        .db()
        .newQuery(`
      INSERT OR IGNORE INTO collection_recipes (id, collection, recipe, created, updated)
      VALUES ({:id}, {:collection}, {:recipe}, '2026-01-01 00:00:00.000Z', '2026-01-01 00:00:00.000Z')
    `)
        .bind({
          id: cr.id,
          collection: cr.collection,
          recipe: cr.recipe,
        })
        .execute()
    }

    // 6. Selected Recipes (5 items)
    const selectedRecipes = [
      { id: 'bokl8vwgg5uylj4', user: 'juq99gi95gizj1g', recipe: '01mnozc41d4ir1d' },
      { id: 'vk5o40m213ujhc5', user: 'juq99gi95gizj1g', recipe: '3673d2jrng148w1' },
      { id: '6ostw3x31ds9ena', user: 'juq99gi95gizj1g', recipe: '9bk39umkggg6ml8' },
      { id: 'gl8xfe38ncyuqlt', user: 'juq99gi95gizj1g', recipe: '59qeb8f84whi3qg' },
      { id: 'y3xygjsplgs2cdu', user: 'juq99gi95gizj1g', recipe: '44pdvbobj9rgw8n' },
    ]

    for (const sr of selectedRecipes) {
      app
        .db()
        .newQuery(`
      INSERT OR IGNORE INTO selected_recipes (id, user, recipe, created, updated)
      VALUES ({:id}, {:user}, {:recipe}, '2026-01-01 00:00:00.000Z', '2026-01-01 00:00:00.000Z')
    `)
        .bind({
          id: sr.id,
          user: sr.user,
          recipe: sr.recipe,
        })
        .execute()
    }
  },
  (app) => {
    const selectedRecipeIds = [
      'bokl8vwgg5uylj4',
      'vk5o40m213ujhc5',
      '6ostw3x31ds9ena',
      'gl8xfe38ncyuqlt',
      'y3xygjsplgs2cdu',
    ]
    for (const id of selectedRecipeIds) {
      app.db().newQuery(`DELETE FROM selected_recipes WHERE id = {:id}`).bind({ id }).execute()
    }

    const collectionRecipeIds = [
      'px79sshg2r2ni8f',
      'dso1c5l0r23dfyt',
      'jfbcafinmqw0fhw',
      'vf5ti0fdvdxun8s',
      '0kgb9sq8ijflowv',
    ]
    for (const id of collectionRecipeIds) {
      app.db().newQuery(`DELETE FROM collection_recipes WHERE id = {:id}`).bind({ id }).execute()
    }

    app.db().newQuery(`DELETE FROM collections WHERE id = '1ilu9i0atcmt3e9'`).execute()

    const recipeIds = [
      'jvqla5a8c19ctn6',
      'rpqsxruc7xz6v4p',
      'jcd5dvv1oynx06n',
      'ur01753dx1w7zoy',
      '01mnozc41d4ir1d',
      'wxa1xo0pyu32au0',
      '44pdvbobj9rgw8n',
      '4it94vggpidx6m5',
      'vmmil0mscobt5ub',
      'kk1hywa1t80at95',
      '59qeb8f84whi3qg',
      'x1jwfanehtfguu7',
      'lhowxac3wpee40i',
      'u9zh2a4krzt71dc',
      '3673d2jrng148w1',
      '9bk39umkggg6ml8',
    ]
    for (const id of recipeIds) {
      app.db().newQuery(`DELETE FROM recipes WHERE id = {:id}`).bind({ id }).execute()
    }

    const techniqueIds = [
      '8x34daskv521lbv',
      'xoe3noh2zlm42fj',
      '94f6muo6r06kqpe',
      'iti1ktj4senrrfi',
      '48gtns7lr4cuvrd',
      'vryemo4ldy13a55',
      'k6dkthl2rz6cncm',
      'fnh60eujqj5wzaf',
      '0f9ilablmvmjbn9',
      '2e9pv0iuy5oyikr',
      '01i6q3sjc6rsqrk',
    ]
    for (const id of techniqueIds) {
      app.db().newQuery(`DELETE FROM techniques WHERE id = {:id}`).bind({ id }).execute()
    }

    const categoryIds = [
      'w07frp7mq5n1c2t',
      'kyzo380gbz9z7s4',
      'mfy0298jd07p8uv',
      'ds0uxvexb4s4ev3',
      '7og9o9ge1c7ab0l',
      '1qsmth7dfiisfde',
      'io42hqrqdh3kl44',
      'u07wm94f57ltivx',
      'jrurz240bvsdq2l',
      'gp0r5mnb3x78ibr',
    ]
    for (const id of categoryIds) {
      app.db().newQuery(`DELETE FROM categories WHERE id = {:id}`).bind({ id }).execute()
    }
  },
)
